<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class AttachmentType extends Model
{


    use SoftDeletes;
    protected $fillable = [
        'type',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($type){

            $type->attachments()->each(function ($attachment){
                $attachment->delete();
            });
        });
    }

    public function attachments(){
        return $this->hasMany(Attachment::class,'attachmentType_id');
    }
}
