<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\File;
use function foo\func;

class Attachment extends Model
{
    use SoftDeletes;

    protected $with = ['type'];
    protected $fillable = [
        'src',
        'products_id',
        'attachmentType_id',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($attachment){

            File::delete(public_path('files/products/'. $attachment->src));

        });
    }

    public function product(){
        return $this->belongsTo(Products::class);
    }

    public function type(){
        return $this->belongsTo(AttachmentType::class,'attachmentType_id');
    }



}
