<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Illuminate\Support\Facades\Event;

class Categories extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'parent_id',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($category){

            foreach ($category->products as $product){
                $product->category_id = null;
                $product->save();
            }

            foreach ($category->children as $child){
                $child->parent_id = null;
                $child->save();
            }

        });
    }


    public function products(){
        return $this->hasMany(Products::class,'category_id');
    }

    public function TopProducts(int $limit = 5){
        return $this->hasMany(Products::class,'category_id')->orderBy('viewed','desc');
    }


    public function parent(){
        return $this->belongsTo(Categories::class);
    }
    public function children(){
        return $this->hasMany(Categories::class,'parent_id');
    }


}
