<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use function foo\func;

class Companies extends Model
{

    use SoftDeletes;
    protected $fillable = [
        'name',
        'phone',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($company){
            $company->branches()->each(function ($branch){
                    $branch->delete();
            });
        });


    }

    public function branches(){
        return $this->hasMany(Branches::class,'company_id');
    }
}
