<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Groups extends Model
{

    use SoftDeletes;
    protected $fillable = [
        'name',

    ];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($group){

            foreach ($group->products as $product){
                $product->group_id = null;
                $product->save();
            }

        });
    }


    public function products(){
        return $this->hasMany(Products::class,'group_id');
    }
}
