<?php

namespace App;

use Carbon\Carbon;
use Faker\Provider\Base;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Offers extends Model
{

    use SoftDeletes;
    protected $fillable = [
        'price',
        'start',
        'end',
        'number',
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope('end', function (Builder $builder) {
            $builder->whereDate('end', '>', Carbon::now());
        });
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleting(function ($offer){
            $offer->products()->detach();
        });
    }

    public function products(){
        return $this->belongsToMany(Products::class)->withPivot(['quantity']);
    }

    public function orders(){
        return $this->belongsToMany(Orders::class);
    }

    public function branch(){
        return $this->belongsTo(Branches::class);
    }

    /**
     * Return the String of a SWIFT/BIC number
     *
     * @example 'RZTIAT22263'
     * @link    http://en.wikipedia.org/wiki/ISO_9362
     * @return  string Swift/Bic number
     */
    public static function randomOfferNumber(){
        return Base::regexify("^([0-9]){2}([A-Z]){1}([0-9]){1}");
    }
}
