<?php

namespace App\Http\Requests\Group;

use Illuminate\Foundation\Http\FormRequest;

class StoreGroup extends FormRequest
{

    private $table = 'groups';
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required|min:2|max:100|unique:'. $this->table .',name',
        ];
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }

}
